[package]
authors = ["josh rotenberg <joshrotenberg@gmail.com>"]
description = "Architectural Decision Record command line tool"
documentation = "https://docs.rs/adrs"
edition = "2018"
homepage = "https://github.com/joshrotenberg/adrs"
license = "MIT/Apache-2.0"
name = "adrs"
readme = "README.md"
repository = "https://github.com/joshrotenberg/adrs.git"
version = "0.1.0"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
