[package]
name = "adrs"
version = "0.1.0"
authors = ["josh rotenberg <joshrotenberg@gmail.com>"]
description = "Architectural Decision Record command line tool"
license = "MIT/Apache-2.0"
homepage = "https://github.com/joshrotenberg/adrs"
repository = "https://github.com/joshrotenberg/adrs.git"
documentation = "https://docs.rs/adrs"
readme = "README.md"
edition = "2018"

[lib]
name = "adrs"
path = "src/adrs/lib.rs" 

[[bin]]
name = "adrs"

[dependencies]
clap = "2.33.3"
chrono = "0.4"
handlebars = "3.5.3"
thiserror = "1.0"
heck = "0.3.1"