name: CI
on: [push, pull_request]

env:
  EDITOR: cat
  VISUAL: cat

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13-xl, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo fetch
      - name: cargo test build
        run: cargo build --tests --release
      - name: cargo test
        run: cargo test --release